load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "name_mangling",
    hdrs = ["name_mangling.h"],
)

cc_library(
    name = "protocol",
    srcs = [
        "conformance.hh",
        "member_function_thunks.hh",
        "operator_thunks.hh",
        "overload_spec.hh",
        "protocol_traits.hh",
        "protocol_wrappers.hh",
        "vtable.hh",
    ],
    hdrs = ["protocol.hh"],
    deps = [
        ":name_mangling",
    ],
)

cc_library(
    name = "consteval_check",
    hdrs = ["consteval_check.h"],
)

cc_test(
    name = "protocol_test",
    size = "small",
    srcs = [
        "allocator_tests.cc",
        "consteval_check_test.cc",
        "forwarding_test.cc",
        "name_mangling_tests.cc",
        "protocol_test.cc",
        "tagged_allocator.h",
        "test_helpers.h",
        "tracking_allocator.h",
    ],
    deps = [
        ":consteval_check",
        ":protocol",
        "@googletest//:gtest_main",
    ],
)
