/* Copyright (c) 2026 The XYZ Protocol Authors. All Rights Reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
==============================================================================*/
// ============================================================================
// AUTOMATICALLY GENERATED FILE - DO NOT MODIFY
// ============================================================================
// This file was generated by scripts/generate_operator_forwarders.py.
//
// One operator_forwarder specialization pair (non-const, const) plus one
// operator_join specialization per operator kind, for the C++26 reflection
// backend: forwarding an interface operator requires a real `operator<symbol>`
// declaration, and the symbol must appear as a literal token in source, so
// each kind is generated once here rather than reimplemented by hand.
//
// Any manual changes made to this file will be overwritten during the next
// generation run.
// ============================================================================
#ifndef XYZ_PROTOCOL_REFLECTION_DETAIL_OPERATOR_FORWARDERS_H_
#define XYZ_PROTOCOL_REFLECTION_DETAIL_OPERATOR_FORWARDERS_H_

#ifndef __cpp_impl_reflection
#error \
    "This header requires a compiler with C++26 reflection support (GCC 16+, -std=c++26 -freflection)."
#endif

#include <meta>
#include <utility>

namespace xyz {
namespace reflection_detail {

using std::meta::info;

template <typename Owner, info Member, typename Signature,
          std::meta::operators Kind, bool ConstCall, bool IsNoexcept>
struct operator_forwarder;

// One join per operator kind gathers every overload of that kind into a
// single class: name lookup for e.g. `operator+` across multiple distinct
// bases would be ambiguous, so the overloads must be merged with
// using-declarations, which also require the operator symbol literally.
template <std::meta::operators Kind, typename... Forwarders>
struct operator_join;

// op_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_equals, false, IsNoexcept> {
  ReturnType operator=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_equals, true, IsNoexcept> {
  ReturnType operator=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator=...;
};

// op_parentheses
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_parentheses, false,
                          IsNoexcept> {
  ReturnType operator()(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_parentheses, true,
                          IsNoexcept> {
  ReturnType operator()(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_parentheses, Forwarders...>
    : Forwarders... {
  using Forwarders::operator()...;
};

// op_square_brackets
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_square_brackets, false,
                          IsNoexcept> {
  ReturnType operator[](ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_square_brackets, true,
                          IsNoexcept> {
  ReturnType operator[](ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_square_brackets, Forwarders...>
    : Forwarders... {
  using Forwarders::operator[]...;
};

// op_arrow
template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::op_arrow, false, IsNoexcept> {
  ReturnType operator->() noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }
};

template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::op_arrow, true, IsNoexcept> {
  ReturnType operator->() const noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_arrow, Forwarders...>
    : Forwarders... {
  using Forwarders::operator->...;
};

// op_arrow_star
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_arrow_star, false,
                          IsNoexcept> {
  ReturnType operator->*(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_arrow_star, true,
                          IsNoexcept> {
  ReturnType operator->*(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_arrow_star, Forwarders...>
    : Forwarders... {
  using Forwarders::operator->*...;
};

// op_tilde
template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::op_tilde, false, IsNoexcept> {
  ReturnType operator~() noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }
};

template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::op_tilde, true, IsNoexcept> {
  ReturnType operator~() const noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_tilde, Forwarders...>
    : Forwarders... {
  using Forwarders::operator~...;
};

// op_exclamation
template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::op_exclamation, false,
                          IsNoexcept> {
  ReturnType operator!() noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }
};

template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::op_exclamation, true,
                          IsNoexcept> {
  ReturnType operator!() const noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_exclamation, Forwarders...>
    : Forwarders... {
  using Forwarders::operator!...;
};

// op_plus
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_plus, false, IsNoexcept> {
  ReturnType operator+(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_plus, true, IsNoexcept> {
  ReturnType operator+(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_plus, Forwarders...>
    : Forwarders... {
  using Forwarders::operator+...;
};

// op_minus
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_minus, false, IsNoexcept> {
  ReturnType operator-(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_minus, true, IsNoexcept> {
  ReturnType operator-(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_minus, Forwarders...>
    : Forwarders... {
  using Forwarders::operator-...;
};

// op_star
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_star, false, IsNoexcept> {
  ReturnType operator*(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_star, true, IsNoexcept> {
  ReturnType operator*(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_star, Forwarders...>
    : Forwarders... {
  using Forwarders::operator*...;
};

// op_slash
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_slash, false, IsNoexcept> {
  ReturnType operator/(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_slash, true, IsNoexcept> {
  ReturnType operator/(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_slash, Forwarders...>
    : Forwarders... {
  using Forwarders::operator/...;
};

// op_percent
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_percent, false, IsNoexcept> {
  ReturnType operator%(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_percent, true, IsNoexcept> {
  ReturnType operator%(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_percent, Forwarders...>
    : Forwarders... {
  using Forwarders::operator%...;
};

// op_caret
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_caret, false, IsNoexcept> {
  ReturnType operator^(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_caret, true, IsNoexcept> {
  ReturnType operator^(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_caret, Forwarders...>
    : Forwarders... {
  using Forwarders::operator^...;
};

// op_ampersand
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_ampersand, false,
                          IsNoexcept> {
  ReturnType operator&(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_ampersand, true,
                          IsNoexcept> {
  ReturnType operator&(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_ampersand, Forwarders...>
    : Forwarders... {
  using Forwarders::operator&...;
};

// op_pipe
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_pipe, false, IsNoexcept> {
  ReturnType operator|(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_pipe, true, IsNoexcept> {
  ReturnType operator|(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_pipe, Forwarders...>
    : Forwarders... {
  using Forwarders::operator|...;
};

// op_plus_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_plus_equals, false,
                          IsNoexcept> {
  ReturnType operator+=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_plus_equals, true,
                          IsNoexcept> {
  ReturnType operator+=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_plus_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator+=...;
};

// op_minus_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_minus_equals, false,
                          IsNoexcept> {
  ReturnType operator-=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_minus_equals, true,
                          IsNoexcept> {
  ReturnType operator-=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_minus_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator-=...;
};

// op_star_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_star_equals, false,
                          IsNoexcept> {
  ReturnType operator*=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_star_equals, true,
                          IsNoexcept> {
  ReturnType operator*=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_star_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator*=...;
};

// op_slash_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_slash_equals, false,
                          IsNoexcept> {
  ReturnType operator/=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_slash_equals, true,
                          IsNoexcept> {
  ReturnType operator/=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_slash_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator/=...;
};

// op_percent_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_percent_equals, false,
                          IsNoexcept> {
  ReturnType operator%=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_percent_equals, true,
                          IsNoexcept> {
  ReturnType operator%=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_percent_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator%=...;
};

// op_caret_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_caret_equals, false,
                          IsNoexcept> {
  ReturnType operator^=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_caret_equals, true,
                          IsNoexcept> {
  ReturnType operator^=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_caret_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator^=...;
};

// op_ampersand_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_ampersand_equals, false,
                          IsNoexcept> {
  ReturnType operator&=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_ampersand_equals, true,
                          IsNoexcept> {
  ReturnType operator&=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_ampersand_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator&=...;
};

// op_pipe_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_pipe_equals, false,
                          IsNoexcept> {
  ReturnType operator|=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_pipe_equals, true,
                          IsNoexcept> {
  ReturnType operator|=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_pipe_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator|=...;
};

// op_equals_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_equals_equals, false,
                          IsNoexcept> {
  ReturnType operator==(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_equals_equals, true,
                          IsNoexcept> {
  ReturnType operator==(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_equals_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator==...;
};

// op_exclamation_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_exclamation_equals, false,
                          IsNoexcept> {
  ReturnType operator!=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_exclamation_equals, true,
                          IsNoexcept> {
  ReturnType operator!=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_exclamation_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator!=...;
};

// op_less
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less, false, IsNoexcept> {
  ReturnType operator<(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less, true, IsNoexcept> {
  ReturnType operator<(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_less, Forwarders...>
    : Forwarders... {
  using Forwarders::operator<...;
};

// op_greater
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater, false, IsNoexcept> {
  ReturnType operator>(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater, true, IsNoexcept> {
  ReturnType operator>(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_greater, Forwarders...>
    : Forwarders... {
  using Forwarders::operator>...;
};

// op_less_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less_equals, false,
                          IsNoexcept> {
  ReturnType operator<=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less_equals, true,
                          IsNoexcept> {
  ReturnType operator<=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_less_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator<=...;
};

// op_greater_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater_equals, false,
                          IsNoexcept> {
  ReturnType operator>=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater_equals, true,
                          IsNoexcept> {
  ReturnType operator>=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_greater_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator>=...;
};

// op_spaceship
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_spaceship, false,
                          IsNoexcept> {
  ReturnType operator<=>(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_spaceship, true,
                          IsNoexcept> {
  ReturnType operator<=>(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_spaceship, Forwarders...>
    : Forwarders... {
  using Forwarders::operator<=>...;
};

// op_ampersand_ampersand
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_ampersand_ampersand, false,
                          IsNoexcept> {
  ReturnType operator&&(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_ampersand_ampersand, true,
                          IsNoexcept> {
  ReturnType operator&&(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_ampersand_ampersand,
                     Forwarders...> : Forwarders... {
  using Forwarders::operator&&...;
};

// op_pipe_pipe
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_pipe_pipe, false,
                          IsNoexcept> {
  ReturnType operator||(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_pipe_pipe, true,
                          IsNoexcept> {
  ReturnType operator||(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_pipe_pipe, Forwarders...>
    : Forwarders... {
  using Forwarders::operator||...;
};

// op_less_less
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less_less, false,
                          IsNoexcept> {
  ReturnType operator<<(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less_less, true,
                          IsNoexcept> {
  ReturnType operator<<(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_less_less, Forwarders...>
    : Forwarders... {
  using Forwarders::operator<<...;
};

// op_greater_greater
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater_greater, false,
                          IsNoexcept> {
  ReturnType operator>>(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater_greater, true,
                          IsNoexcept> {
  ReturnType operator>>(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_greater_greater, Forwarders...>
    : Forwarders... {
  using Forwarders::operator>>...;
};

// op_less_less_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less_less_equals, false,
                          IsNoexcept> {
  ReturnType operator<<=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_less_less_equals, true,
                          IsNoexcept> {
  ReturnType operator<<=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_less_less_equals, Forwarders...>
    : Forwarders... {
  using Forwarders::operator<<=...;
};

// op_greater_greater_equals
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater_greater_equals,
                          false, IsNoexcept> {
  ReturnType operator>>=(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_greater_greater_equals, true,
                          IsNoexcept> {
  ReturnType operator>>=(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_greater_greater_equals,
                     Forwarders...> : Forwarders... {
  using Forwarders::operator>>=...;
};

// op_plus_plus
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_plus_plus, false,
                          IsNoexcept> {
  ReturnType operator++(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_plus_plus, true,
                          IsNoexcept> {
  ReturnType operator++(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_plus_plus, Forwarders...>
    : Forwarders... {
  using Forwarders::operator++...;
};

// op_minus_minus
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_minus_minus, false,
                          IsNoexcept> {
  ReturnType operator--(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_minus_minus, true,
                          IsNoexcept> {
  ReturnType operator--(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_minus_minus, Forwarders...>
    : Forwarders... {
  using Forwarders::operator--...;
};

// op_comma
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_comma, false, IsNoexcept> {
  ReturnType operator,(ParameterTypes... parameters) noexcept(IsNoexcept) {
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::op_comma, true, IsNoexcept> {
  ReturnType operator,(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }
};

template <typename... Forwarders>
struct operator_join<std::meta::operators::op_comma, Forwarders...>
    : Forwarders... {
  using Forwarders::operator, ...;
};

}  // namespace reflection_detail
}  // namespace xyz

#endif  // XYZ_PROTOCOL_REFLECTION_DETAIL_OPERATOR_FORWARDERS_H_
