#!/usr/bin/env python3
"""
Measure which consteval code in the protocol headers the test suite evaluates.

`consteval` code executes inside the compiler's constant evaluator, never at
runtime, so runtime coverage tools cannot see it: GCC's `--coverage`
instrumentation marks every line of a consteval function as non-executable,
and a consteval function no test evaluates is indistinguishable from one that
is thoroughly tested. The community workaround for `constexpr` code - run
every test at both compile time and runtime so runtime instrumentation
observes it - is unavailable here: immediate functions cannot execute at
runtime, and calling a P2996 metafunction makes the caller immediate too.

This tool measures consteval coverage by compile-time trap probing. A
constant evaluation is isolated - no side effect escapes it - but it can
abort compilation, and that one bit per evaluation is enough:

1. Instrument a copy of every library header, inserting a call to a `trap`
   function template at the start of every block and before every `return`
   and `throw` statement inside consteval code. Insertions stay on the
   original line, so line numbers are unchanged. Each trap is keyed on its
   header's index and its line; it is a no-op unless that key is armed, in
   which case it throws during constant evaluation, and the compiler's
   uncaught-exception diagnostic names the key.
2. Compile a probe translation unit with `-fsyntax-only` (constant evaluation
   happens during semantic analysis) with every probe point not yet known to
   be covered armed at once. GCC does not stop at the first error: each
   independent top-level constant evaluation throws at most once, naming
   the first armed trap on its path, and every such failure is reported in
   the same compile. A trap that always runs after another armed trap on
   the same path is masked, so the round is repeated with the newly found
   traps disarmed until a round finds nothing. Splitting the armed set into
   interleaved batches, one compile each, keeps neighbouring traps out of
   each other's way and uses every core.
3. Repeat step 2 for each translation unit, cheapest to compile first, so
   the expensive ones only ever arm what the cheap ones left uncovered.
4. Report evaluated and unevaluated probe points, optionally as an LCOV
   trace file that merges cleanly with runtime gcov data (the two are
   disjoint: gcov reports nothing for consteval lines).

Limitations: probe points sit at block and return/throw granularity, not on
every line; a branch of `if constexpr` that no instantiation includes is
reported unevaluated (correctly so); and a `catch (...)` that swallowed the
trap exception without rethrowing would mask probes beneath it (none of the
instrumented headers has one).

Requires a reflection-capable GCC (found via compiler_discovery) and a prior
`./scripts/cmake.sh build` to provide the googletest headers.
"""

import argparse
import concurrent.futures
import dataclasses
import glob
import os
import re
import shutil
import subprocess
import sys

from compiler_discovery import find_reflection_compilers

SOURCE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Library headers use the .hh suffix; test helpers (.h) are not instrumented.
INSTRUMENTED_HEADERS = sorted(
    os.path.basename(path) for path in glob.glob(os.path.join(SOURCE_ROOT, "*.hh"))
)

TRAP_HEADER = "consteval_coverage_probe.h"

WORK_DIR_MARKER = ".consteval_coverage"

# Header index, then line: `trap_hit<3, 42>` in the diagnostic. Template
# arguments render as plain digits whatever the locale, unlike a value in
# braces, whose surrounding quotes GCC may render as Unicode.
TRAP_ERROR_PATTERN = re.compile(r"consteval_coverage_probe::trap_hit<(\d+), (\d+)>")

# Translation units that instantiate protocols and so drive the consteval
# machinery in the instrumented headers, cheapest to compile first: each
# only arms the probe points the ones before it left uncovered.
DEFAULT_TRANSLATION_UNITS = [
    "vtable_tests.cc",
    "name_mangling_tests.cc",
    "allocator_tests.cc",
    "forwarding_test.cc",
    "protocol_operator_tests.cc",
    "protocol_test.cc",
]

ProbeKey = tuple[int, int]  # (header index, line number)


def trap_call(header_index: int) -> str:
    """Return the trap statement to insert into the header at `header_index`."""
    return f"::xyz::consteval_coverage_probe::trap<{header_index}, __LINE__>();"


def trap_header_content(armed: frozenset[ProbeKey]) -> str:
    """Generate the trap header with `armed` baked in as specializations."""
    specializations = "\n".join(
        f"template <> constexpr bool armed<{header_index}, {line}> = true;"
        for header_index, line in sorted(armed)
    )
    return f"""\
// Generated by scripts/consteval_coverage.py; force-included into the
// instrumented translation units via -include.
namespace xyz::consteval_coverage_probe {{

// Deliberately not derived from std::exception, so that no typed catch in
// the library or its tests can swallow it. The key is carried in the type
// so that the uncaught-exception diagnostic names it.
template <int Header, long Line>
struct trap_hit {{}};

template <int Header, long Line>
constexpr bool armed = false;
{specializations}

// `if constexpr` so that an unarmed trap costs the constant evaluator
// nothing.
template <int Header, long Line>
constexpr void trap() {{
  if consteval {{
    if constexpr (armed<Header, Line>) throw trap_hit<Header, Line>{{}};
  }}
}}

}}  // namespace xyz::consteval_coverage_probe
"""


# Tokens whose presence directly before `{` marks it as opening a compound
# statement rather than a braced initialiser. `)` covers control clauses,
# function signatures and lambdas; `consteval` covers consteval blocks.
BLOCK_OPEN_TOKENS = {")", "else", "try", "do", "consteval"}

# Tokens after which a `return` or `throw` token starts a statement.
STATEMENT_START_TOKENS = {";", "{", "}", ")", ":", "else", "do"}


@dataclasses.dataclass
class ProbePoint:
    """One instrumented location in the original source."""

    header: str
    header_index: int
    line_number: int
    enclosing_function: str
    source_text: str

    @property
    def key(self) -> ProbeKey:
        """Return the trap key the instrumented line carries."""
        return (self.header_index, self.line_number)


class Instrumenter:
    """
    Insert coverage traps into the consteval regions of a C++ header.

    A hand-rolled scanner rather than a real C++ parser: it tracks strings,
    comments, brace depth and consteval regions, which the clang-formatted
    source keeps tractable. It only ever inserts text within a line, so the
    instrumented file has the same line numbers as the original.
    Unrecognised constructs are left uninstrumented (under-measurement,
    never miscompilation); a compile that fails without any trap firing is
    reported as an instrumenter bug.
    """

    def __init__(self, header: str, header_index: int) -> None:
        """Initialise scanner state for instrumenting `header`."""
        self.header = header
        self.header_index = header_index
        self.trap_call = trap_call(header_index)
        self.brace_depth = 0
        self.paren_depth = 0
        # Brace depths at which enclosing consteval regions opened, and the
        # name of the consteval function each region belongs to.
        self.region_stack: list[int] = []
        self.function_stack: list[str] = []
        # A `consteval` token was seen; the next block-opening `{` starts a
        # region named `pending_function_name` (the identifier before the
        # first `(` of the pending declaration, if any).
        self.pending_consteval = False
        self.pending_function_name = ""
        self.pending_name_frozen = False
        self.in_block_comment = False
        # Set when a `switch` header is seen; its block gets no entry trap
        # because a statement before the first case label is unreachable.
        self.suppress_next_block_trap = False
        self.last_token = ""
        # While wrapping `return expr;` as `{ trap; return expr; }`: the
        # parenthesis/bracket nesting until the terminating `;`.
        self.wrap_nesting: int | None = None
        # `+[` introduces a captureless lambda converted to a function
        # pointer: a runtime thunk stored in a vtable. Its body executes at
        # runtime (gcov's domain, not the constant evaluator's), so probes
        # inside it are suppressed. The stack holds the brace depth of each
        # such lambda body.
        self.pending_runtime_lambda = False
        self.runtime_lambda_stack: list[int] = []
        self.probe_points: list[ProbePoint] = []

    def in_consteval_region(self) -> bool:
        """Return whether the scanner is inside compile-time-evaluated code."""
        return bool(self.region_stack) and not self.runtime_lambda_stack

    def instrument(self, source_lines: list[str]) -> list[str]:
        """Return instrumented copies of `source_lines` (without newlines)."""
        return [
            self._instrument_line(line, line_number)
            for line_number, line in enumerate(source_lines, start=1)
        ]

    def _record_probe(self, line_number: int, original_line: str) -> None:
        enclosing = self.function_stack[-1] if self.function_stack else "<none>"
        if self.pending_consteval:
            enclosing = self.pending_function_name
        if not self.probe_points or self.probe_points[-1].line_number != line_number:
            self.probe_points.append(
                ProbePoint(
                    self.header,
                    self.header_index,
                    line_number,
                    enclosing,
                    original_line.strip(),
                )
            )

    def _instrument_line(self, line: str, line_number: int) -> str:
        if not self.in_block_comment and line.lstrip().startswith("#"):
            return line
        output: list[str] = []
        index = 0
        while index < len(line):
            if self.in_block_comment:
                end = line.find("*/", index)
                if end == -1:
                    output.append(line[index:])
                    break
                output.append(line[index : end + 2])
                index = end + 2
                self.in_block_comment = False
                continue
            character = line[index]
            if character.isalpha() or character == "_":
                end = index + 1
                while end < len(line) and (line[end].isalnum() or line[end] == "_"):
                    end += 1
                token = line[index:end]
                output.append(self._on_token(token, line, line_number))
                index = end
                continue
            if line.startswith("//", index):
                output.append(line[index:])
                break
            if line.startswith("/*", index):
                output.append("/*")
                index += 2
                self.in_block_comment = True
                continue
            if character == '"' or (
                character == "'"
                and not (
                    index > 0 and (line[index - 1].isalnum() or line[index - 1] == "_")
                )
            ):
                end = self._literal_end(line, index, character)
                output.append(line[index:end])
                index = end
                continue
            output.append(self._on_punctuation(character, line, line_number))
            index += 1
        return "".join(output)

    def _literal_end(self, line: str, start: int, quote: str) -> int:
        index = start + 1
        while index < len(line):
            if line[index] == "\\":
                index += 2
                continue
            if line[index] == quote:
                return index + 1
            index += 1
        return index

    def _on_token(self, token: str, line: str, line_number: int) -> str:
        prefix = ""
        if token == "consteval" and self.wrap_nesting is None:
            self.pending_consteval = True
            self.pending_name_frozen = False
            self.pending_function_name = f"<consteval block at line {line_number}>"
        elif token == "switch":
            self.suppress_next_block_trap = True
        elif (
            token in ("return", "throw")
            and self.in_consteval_region()
            and self.wrap_nesting is None
            and self.last_token in STATEMENT_START_TOKENS
        ):
            self._record_probe(line_number, line)
            prefix = "{ " + self.trap_call + " "
            self.wrap_nesting = 0
        elif (
            self.pending_consteval
            and not self.pending_name_frozen
            and token not in ("consteval", "static")
        ):
            self.pending_function_name = token
        self.last_token = token
        return prefix + token

    def _on_punctuation(self, character: str, line: str, line_number: int) -> str:
        if character == "{":
            return self._on_open_brace(line, line_number)
        if character == "}":
            self._on_close_brace()
            self.last_token = "}"
            return "}"
        if character in "([":
            if character == "(" and self.pending_consteval:
                self.pending_name_frozen = True
            if character == "[" and self.last_token == "+":
                self.pending_runtime_lambda = True
            self.paren_depth += 1
            if self.wrap_nesting is not None:
                self.wrap_nesting += 1
        elif character in ")]":
            self.paren_depth -= 1
            if self.wrap_nesting is not None:
                self.wrap_nesting -= 1
        elif character == ";":
            if self.wrap_nesting == 0:
                self.wrap_nesting = None
                self.last_token = ";"
                return "; }"
            if self.paren_depth == 0 and self.brace_depth == 0:
                # A declaration (e.g. a forward declaration) ended before any
                # body opened; it cannot start a consteval region.
                self.pending_consteval = False
        if not character.isspace():
            self.last_token = character
        return character

    def _on_open_brace(self, line: str, line_number: int) -> str:
        self.brace_depth += 1
        if self.pending_runtime_lambda:
            # The first `{` after `+[` is the lambda body: a captureless
            # lambda's capture list and parameter list cannot contain braces.
            self.runtime_lambda_stack.append(self.brace_depth)
            self.pending_runtime_lambda = False
            self.last_token = "{"
            return "{"
        is_block_open = self.last_token in BLOCK_OPEN_TOKENS
        if self.pending_consteval and is_block_open:
            self.region_stack.append(self.brace_depth)
            self.function_stack.append(self.pending_function_name)
            self.pending_consteval = False
        if is_block_open and self.suppress_next_block_trap:
            self.suppress_next_block_trap = False
            self.last_token = "{"
            return "{"
        if self.in_consteval_region() and is_block_open:
            self._record_probe(line_number, line)
            # ";" so that a `return` following on the same line still counts
            # as starting a statement.
            self.last_token = ";"
            return "{ " + self.trap_call
        self.last_token = "{"
        return "{"

    def _on_close_brace(self) -> None:
        if self.region_stack and self.brace_depth == self.region_stack[-1]:
            self.region_stack.pop()
            self.function_stack.pop()
        if (
            self.runtime_lambda_stack
            and self.brace_depth == self.runtime_lambda_stack[-1]
        ):
            self.runtime_lambda_stack.pop()
        self.brace_depth -= 1


def find_googletest_include_directories() -> list[str]:
    """
    Locate googletest headers in the checkout CMake used.

    The sandbox image points FETCHCONTENT_SOURCE_DIR_GOOGLETEST at a baked-in
    checkout; elsewhere FetchContent clones under the build directory.
    """
    pattern = os.path.join(SOURCE_ROOT, "build", "*", "_deps", "googletest-src")
    candidates = [os.environ.get("FETCHCONTENT_SOURCE_DIR_GOOGLETEST", "")]
    candidates += sorted(glob.glob(pattern))
    for googletest_source in filter(None, candidates):
        include_directories = [
            os.path.join(googletest_source, "googletest", "include"),
            os.path.join(googletest_source, "googlemock", "include"),
        ]
        if all(os.path.isdir(directory) for directory in include_directories):
            return include_directories
    sys.exit(
        "googletest headers not found under build/*/_deps; run "
        "./scripts/cmake.sh build first"
    )


@dataclasses.dataclass
class ProbeConfiguration:
    """Everything needed to compile one probe batch."""

    compiler: str
    work_dir: str
    include_directories: list[str]
    jobs: int


def populate_work_dir(
    work_dir: str,
    instrumented_by_header: dict[str, list[str]],
    translation_units: list[str],
) -> None:
    """
    Fill `work_dir` with the instrumented headers and everything they need.

    Every root header and each probe translation unit is copied, so that
    every quote-include resolves inside the work directory; nothing falls
    back to an uninstrumented original. A previous run's directory is
    replaced; any other existing directory is left alone.
    """
    marker = os.path.join(work_dir, WORK_DIR_MARKER)
    if os.path.isdir(work_dir):
        if not os.path.exists(marker):
            sys.exit(f"{work_dir} exists and was not created by this script")
        shutil.rmtree(work_dir)
    os.makedirs(work_dir)
    open(marker, "w").close()
    for pattern in ("*.h", "*.hh"):
        for path in glob.glob(os.path.join(SOURCE_ROOT, pattern)):
            shutil.copy(path, work_dir)
    for header, lines in instrumented_by_header.items():
        with open(os.path.join(work_dir, header), "w") as out:
            out.write("\n".join(lines) + "\n")
    for translation_unit in translation_units:
        shutil.copy(os.path.join(SOURCE_ROOT, translation_unit), work_dir)


def compile_batch(
    configuration: ProbeConfiguration,
    translation_unit: str,
    batch_index: int,
    armed: frozenset[ProbeKey],
) -> set[ProbeKey]:
    """Compile `translation_unit` with `armed` armed; return the keys that fired."""
    trap_header = os.path.join(
        configuration.work_dir, f"{translation_unit}.{batch_index}.{TRAP_HEADER}"
    )
    with open(trap_header, "w") as out:
        out.write(trap_header_content(armed))
    command = [
        configuration.compiler,
        "-std=c++26",
        "-freflection",
        "-fsyntax-only",
        "-w",
        "-include",
        trap_header,
    ]
    for directory in configuration.include_directories:
        command.extend(["-I", directory])
    command.append(os.path.join(configuration.work_dir, translation_unit))
    completed = subprocess.run(command, capture_output=True, text=True)
    hits = {
        (int(header_index), int(line))
        for header_index, line in TRAP_ERROR_PATTERN.findall(completed.stderr)
    }
    if completed.returncode != 0 and not hits:
        raise RuntimeError(
            f"instrumented {translation_unit} failed to compile with no trap "
            f"fired; the instrumenter needs fixing:\n{completed.stderr}"
        )
    return hits & armed


def batches(armed: set[ProbeKey], batch_count: int) -> list[frozenset[ProbeKey]]:
    """
    Split `armed` into up to `batch_count` interleaved batches.

    Neighbouring probe points tend to lie on the same evaluation path, where
    the first to run masks the rest, so consecutive keys go to different
    batches.
    """
    ordered = sorted(armed)
    batch_count = max(1, min(batch_count, len(ordered)))
    return [frozenset(ordered[start::batch_count]) for start in range(batch_count)]


def probe_translation_unit(
    configuration: ProbeConfiguration,
    translation_unit: str,
    candidates: set[ProbeKey],
) -> set[ProbeKey]:
    """
    Return the subset of `candidates` that compiling `translation_unit` evaluates.

    Arming many traps in one compile is sound because of two properties.
    A trap throws only when the evaluator executes it, and the diagnostic
    names the trap that threw, so every reported key was evaluated whatever
    else was armed: no false positives. A throw aborts only its own
    top-level constant evaluation, and GCC goes on to report every other
    evaluation that fails, so one compile yields the first armed trap on
    each evaluation's path; the traps after it on that path are masked for
    this round only. The next round disarms everything found so far, so
    each evaluation runs further and reports the next armed trap on its
    path. A trap the test suite evaluates is preceded on its path only by
    traps the suite also evaluates, so it is reported once those are
    disarmed: no permanent false negatives. The armed set shrinks every
    productive round, and a round with no new hits proves no remaining
    armed trap lies on any evaluation path.

    Errors cascading from an aborted evaluation (an incomplete class, a
    missing member) are not trap diagnostics and are ignored; the
    evaluations they suppressed run in a later round once the trap is
    disarmed. A compile that fails with no trap firing raises instead.

    Each round's armed set is split into interleaved batches so that every
    worker has a compile and neighbouring traps do not mask each other.
    """
    covered: set[ProbeKey] = set()
    round_number = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=configuration.jobs) as pool:
        while armed := candidates - covered:
            round_number += 1
            futures = [
                pool.submit(compile_batch, configuration, translation_unit, i, batch)
                for i, batch in enumerate(batches(armed, configuration.jobs))
            ]
            hits: set[ProbeKey] = set()
            for future in concurrent.futures.as_completed(futures):
                hits |= future.result()
            print(
                f"  {translation_unit} round {round_number}: {len(armed)} armed, "
                f"{len(hits)} hit"
            )
            if not hits:
                break
            covered |= hits
    return covered


def write_lcov(
    path: str, probe_points: list[ProbePoint], covered: set[ProbeKey]
) -> None:
    """Write an LCOV trace with one SF/DA block per instrumented header."""
    records = ["TN:consteval"]
    for header in INSTRUMENTED_HEADERS:
        header_probes = [p for p in probe_points if p.header == header]
        if not header_probes:
            continue
        # Repository-relative SF path, matching how Codecov maps files.
        records.append(f"SF:{header}")
        hits = 0
        for probe_point in header_probes:
            hit = int(probe_point.key in covered)
            hits += hit
            records.append(f"DA:{probe_point.line_number},{hit}")
        records.append(f"LH:{hits}")
        records.append(f"LF:{len(header_probes)}")
        records.append("end_of_record")
    with open(path, "w") as trace_file:
        trace_file.write("\n".join(records) + "\n")


def describe(probe_point: ProbePoint) -> str:
    """Return the one-line listing form of `probe_point`."""
    return (
        f"{probe_point.header}:{probe_point.line_number:<4} "
        f"[{probe_point.enclosing_function}] {probe_point.source_text}"
    )


def report(probe_points: list[ProbePoint], covered: set[ProbeKey]) -> None:
    """Print a per-function summary and the unevaluated probe points."""
    by_function: dict[tuple[str, str], list[ProbePoint]] = {}
    for probe_point in probe_points:
        key = (probe_point.header, probe_point.enclosing_function)
        by_function.setdefault(key, []).append(probe_point)

    print("\nconsteval coverage by header and function:")
    for (header, function_name), function_probes in by_function.items():
        hits = sum(1 for p in function_probes if p.key in covered)
        print(f"  {hits:3}/{len(function_probes):<3} {header}: {function_name}")

    uncovered = [p for p in probe_points if p.key not in covered]
    if uncovered:
        print("\nprobe points never evaluated by the test suite:")
        for probe_point in uncovered:
            print(f"  {describe(probe_point)}")

    total = len(probe_points)
    print(
        f"\nconsteval coverage: {len(covered)}/{total} probe points "
        f"evaluated ({100.0 * len(covered) / total:.1f}%)"
    )


def main() -> None:
    """Instrument the library headers, probe every trap and print a report."""
    parser = argparse.ArgumentParser(
        description="Measure consteval test coverage by compile-time trap probing."
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=os.cpu_count() or 1,
        help="Number of parallel probe compilations (default: CPU count)",
    )
    parser.add_argument(
        "--lcov-output",
        help="Also write the result as an LCOV trace file to this path",
    )
    parser.add_argument(
        "--work-dir",
        default=os.path.join(SOURCE_ROOT, "build", "consteval-coverage"),
        help="Directory for instrumented sources (default: build/consteval-coverage)",
    )
    parser.add_argument(
        "--translation-unit",
        action="append",
        help="Probe translation unit, cheapest first (repeatable; default: "
        + ", ".join(DEFAULT_TRANSLATION_UNITS)
        + ")",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List the probe points without compiling anything",
    )
    arguments = parser.parse_args()

    probe_points: list[ProbePoint] = []
    instrumented_by_header: dict[str, list[str]] = {}
    for header_index, header in enumerate(INSTRUMENTED_HEADERS):
        with open(os.path.join(SOURCE_ROOT, header)) as header_file:
            source_lines = header_file.read().splitlines()
        instrumenter = Instrumenter(header, header_index)
        instrumented_by_header[header] = instrumenter.instrument(source_lines)
        probe_points.extend(instrumenter.probe_points)
    if not probe_points:
        sys.exit(f"no consteval probe points found in {INSTRUMENTED_HEADERS}")

    if arguments.list:
        for probe_point in probe_points:
            print(describe(probe_point))
        return

    _, compiler = find_reflection_compilers(dict(os.environ))
    if compiler is None:
        sys.exit(
            "no reflection-capable compiler found (see scripts/compiler_discovery.py)"
        )

    translation_units = arguments.translation_unit or DEFAULT_TRANSLATION_UNITS
    populate_work_dir(arguments.work_dir, instrumented_by_header, translation_units)
    configuration = ProbeConfiguration(
        compiler=compiler,
        work_dir=arguments.work_dir,
        include_directories=find_googletest_include_directories(),
        jobs=arguments.jobs,
    )

    print(
        f"probing {len(probe_points)} consteval probe points in "
        f"{len(instrumented_by_header)} headers against {len(translation_units)} "
        f"translation units with {arguments.jobs} jobs"
    )
    candidates = {probe_point.key for probe_point in probe_points}
    covered: set[ProbeKey] = set()
    for translation_unit in translation_units:
        covered |= probe_translation_unit(
            configuration, translation_unit, candidates - covered
        )

    report(probe_points, covered)
    if arguments.lcov_output:
        write_lcov(arguments.lcov_output, probe_points, covered)
        print(f"LCOV trace written to {arguments.lcov_output}")


if __name__ == "__main__":
    main()
