#!/usr/bin/env python3
"""
Measure which consteval code in the protocol headers the test suite evaluates.

`consteval` code executes inside the compiler's constant evaluator, never at
runtime, so runtime coverage tools cannot see it: GCC's `--coverage`
instrumentation marks every line of a consteval function as non-executable,
and a consteval function no test evaluates is indistinguishable from one that
is thoroughly tested. The community workaround for `constexpr` code - run
every test at both compile time and runtime so runtime instrumentation
observes it - is unavailable here: immediate functions cannot execute at
runtime, and calling a P2996 metafunction makes the caller immediate too.

This tool measures consteval coverage by compile-time trap probing. A
constant evaluation is isolated - no side effect escapes it - but it can
abort compilation, and that one bit per compile is enough:

1. Instrument a copy of each header in INSTRUMENTED_HEADERS, inserting a
   call to a `trap` function at the start of every block and before every
   `return` and `throw` statement inside consteval code. Insertions stay on
   the original line, so line numbers are unchanged. A trap is a no-op
   unless its line number matches the XYZ_CONSTEVAL_COVERAGE_ARMED_LINE
   macro, in which case it throws during constant evaluation, failing the
   build with a recognisable error.
2. Probe one header at a time, with only that header instrumented; every
   other instrumented header is copied in its plain, uninstrumented form
   so a quote-include reaches it locally instead of falling back to its
   original in SOURCE_ROOT, keeping a bare line number a unique probe.
   Compile the probe translation units once per trap line with
   `-fsyntax-only` (constant evaluation happens during semantic
   analysis), arming one line at a time. A failed compile means the test
   suite evaluated that line.
3. Report evaluated and unevaluated probe points, optionally as an LCOV
   trace file that merges cleanly with runtime gcov data (the two are
   disjoint: gcov reports nothing for consteval lines).

Limitations: probe points sit at block and return/throw granularity, not on
every line; a branch of `if constexpr` that no instantiation includes is
reported unevaluated (correctly so); and a `catch (...)` that swallowed the
trap exception without rethrowing would mask probes beneath it (none of the
instrumented headers do).

Requires a reflection-capable GCC (found via compiler_discovery) and a prior
`./scripts/cmake.sh build` to provide the googletest headers.
"""

import argparse
import concurrent.futures
import dataclasses
import glob
import os
import shutil
import subprocess
import sys

from compiler_discovery import find_reflection_compilers

SOURCE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Headers that carry consteval machinery for protocol/protocol_view, split
# out of the former monolithic protocol.hh.
INSTRUMENTED_HEADERS = [
    "protocol.hh",
    "conformance.hh",
    "vtable.hh",
    "member_function_thunks.hh",
    "operator_thunks.hh",
    "protocol_wrappers.hh",
    "name_mangling.h",
]

TRAP_HEADER = "consteval_coverage_probe.h"

TRAP_CALL = "::xyz::consteval_coverage_probe::trap(__LINE__);"

TRAP_ERROR_MARKER = "consteval_coverage_probe"

# Translation units that instantiate protocols and so drive the consteval
# machinery in the instrumented headers.
DEFAULT_TRANSLATION_UNITS = [
    "protocol_test.cc",
    "forwarding_test.cc",
    "allocator_tests.cc",
]

TRAP_HEADER_CONTENT = """\
// Generated by scripts/consteval_coverage.py; force-included into the
// instrumented translation units via -include.
#ifndef XYZ_CONSTEVAL_COVERAGE_ARMED_LINE
#define XYZ_CONSTEVAL_COVERAGE_ARMED_LINE 0
#endif

namespace xyz::consteval_coverage_probe {

// Deliberately not derived from std::exception, so that no typed catch in
// the library or its tests can swallow it.
struct trap_hit {
  long line;
};

constexpr void trap(long line) {
  if consteval {
    if (line == XYZ_CONSTEVAL_COVERAGE_ARMED_LINE) throw trap_hit{line};
  }
}

}  // namespace xyz::consteval_coverage_probe
"""

# Tokens whose presence directly before `{` marks it as opening a compound
# statement rather than a braced initialiser. `)` covers control clauses,
# function signatures and lambdas; `consteval` covers consteval blocks.
BLOCK_OPEN_TOKENS = {")", "else", "try", "do", "consteval"}

# Tokens after which a `return` or `throw` token starts a statement.
STATEMENT_START_TOKENS = {";", "{", "}", ")", ":", "else", "do"}


@dataclasses.dataclass
class ProbePoint:
    """One instrumented location in the original source."""

    header: str
    line_number: int
    enclosing_function: str
    source_text: str


class Instrumenter:
    """
    Insert coverage traps into the consteval regions of a C++ header.

    A hand-rolled scanner rather than a real C++ parser: it tracks strings,
    comments, brace depth and consteval regions, which the clang-formatted
    source keeps tractable. It only ever inserts text within a line, so the
    instrumented file has the same line numbers as the original.
    Unrecognised constructs are left uninstrumented (under-measurement,
    never miscompilation), and the prober verifies that the instrumented
    file still compiles before probing.
    """

    def __init__(self, header: str) -> None:
        """Initialise scanner state for instrumenting `header`."""
        self.header = header
        self.brace_depth = 0
        self.paren_depth = 0
        # Brace depths at which enclosing consteval regions opened, and the
        # name of the consteval function each region belongs to.
        self.region_stack: list[int] = []
        self.function_stack: list[str] = []
        # A `consteval` token was seen; the next block-opening `{` starts a
        # region named `pending_function_name` (the identifier before the
        # first `(` of the pending declaration, if any).
        self.pending_consteval = False
        self.pending_function_name = ""
        self.pending_name_frozen = False
        self.in_block_comment = False
        # Set when a `switch` header is seen; its block gets no entry trap
        # because a statement before the first case label is unreachable.
        self.suppress_next_block_trap = False
        self.last_token = ""
        # While wrapping `return expr;` as `{ trap; return expr; }`: the
        # parenthesis/bracket nesting until the terminating `;`.
        self.wrap_nesting: int | None = None
        # `+[` introduces a captureless lambda converted to a function
        # pointer: a runtime thunk stored in a vtable. Its body executes at
        # runtime (gcov's domain, not the constant evaluator's), so probes
        # inside it are suppressed. The stack holds the brace depth of each
        # such lambda body.
        self.pending_runtime_lambda = False
        self.runtime_lambda_stack: list[int] = []
        self.probe_points: list[ProbePoint] = []

    def in_consteval_region(self) -> bool:
        """Return whether the scanner is inside compile-time-evaluated code."""
        return bool(self.region_stack) and not self.runtime_lambda_stack

    def instrument(self, source_lines: list[str]) -> list[str]:
        """Return instrumented copies of `source_lines` (without newlines)."""
        return [
            self._instrument_line(line, line_number)
            for line_number, line in enumerate(source_lines, start=1)
        ]

    def _record_probe(self, line_number: int, original_line: str) -> None:
        enclosing = self.function_stack[-1] if self.function_stack else "<none>"
        if self.pending_consteval:
            enclosing = self.pending_function_name
        if not self.probe_points or self.probe_points[-1].line_number != line_number:
            self.probe_points.append(
                ProbePoint(self.header, line_number, enclosing, original_line.strip())
            )

    def _instrument_line(self, line: str, line_number: int) -> str:
        if not self.in_block_comment and line.lstrip().startswith("#"):
            return line
        output: list[str] = []
        index = 0
        while index < len(line):
            if self.in_block_comment:
                end = line.find("*/", index)
                if end == -1:
                    output.append(line[index:])
                    break
                output.append(line[index : end + 2])
                index = end + 2
                self.in_block_comment = False
                continue
            character = line[index]
            if character.isalpha() or character == "_":
                end = index + 1
                while end < len(line) and (line[end].isalnum() or line[end] == "_"):
                    end += 1
                token = line[index:end]
                output.append(self._on_token(token, line, line_number))
                index = end
                continue
            if line.startswith("//", index):
                output.append(line[index:])
                break
            if line.startswith("/*", index):
                output.append("/*")
                index += 2
                self.in_block_comment = True
                continue
            if character == '"' or (
                character == "'"
                and not (
                    index > 0 and (line[index - 1].isalnum() or line[index - 1] == "_")
                )
            ):
                end = self._literal_end(line, index, character)
                output.append(line[index:end])
                index = end
                continue
            output.append(self._on_punctuation(character, line, line_number))
            index += 1
        return "".join(output)

    def _literal_end(self, line: str, start: int, quote: str) -> int:
        index = start + 1
        while index < len(line):
            if line[index] == "\\":
                index += 2
                continue
            if line[index] == quote:
                return index + 1
            index += 1
        return index

    def _on_token(self, token: str, line: str, line_number: int) -> str:
        prefix = ""
        if token == "consteval" and self.wrap_nesting is None:
            self.pending_consteval = True
            self.pending_name_frozen = False
            self.pending_function_name = f"<consteval block at line {line_number}>"
        elif token == "switch":
            self.suppress_next_block_trap = True
        elif (
            token in ("return", "throw")
            and self.in_consteval_region()
            and self.wrap_nesting is None
            and self.last_token in STATEMENT_START_TOKENS
        ):
            self._record_probe(line_number, line)
            prefix = "{ " + TRAP_CALL + " "
            self.wrap_nesting = 0
        elif (
            self.pending_consteval
            and not self.pending_name_frozen
            and token not in ("consteval", "static")
        ):
            self.pending_function_name = token
        self.last_token = token
        return prefix + token

    def _on_punctuation(self, character: str, line: str, line_number: int) -> str:
        if character == "{":
            return self._on_open_brace(line, line_number)
        if character == "}":
            self._on_close_brace()
            self.last_token = "}"
            return "}"
        if character in "([":
            if character == "(" and self.pending_consteval:
                self.pending_name_frozen = True
            if character == "[" and self.last_token == "+":
                self.pending_runtime_lambda = True
            self.paren_depth += 1
            if self.wrap_nesting is not None:
                self.wrap_nesting += 1
        elif character in ")]":
            self.paren_depth -= 1
            if self.wrap_nesting is not None:
                self.wrap_nesting -= 1
        elif character == ";":
            if self.wrap_nesting == 0:
                self.wrap_nesting = None
                self.last_token = ";"
                return "; }"
            if self.paren_depth == 0 and self.brace_depth == 0:
                # A declaration (e.g. a forward declaration) ended before any
                # body opened; it cannot start a consteval region.
                self.pending_consteval = False
        if not character.isspace():
            self.last_token = character
        return character

    def _on_open_brace(self, line: str, line_number: int) -> str:
        self.brace_depth += 1
        if self.pending_runtime_lambda:
            # The first `{` after `+[` is the lambda body: a captureless
            # lambda's capture list and parameter list cannot contain braces.
            self.runtime_lambda_stack.append(self.brace_depth)
            self.pending_runtime_lambda = False
            self.last_token = "{"
            return "{"
        is_block_open = self.last_token in BLOCK_OPEN_TOKENS
        if self.pending_consteval and is_block_open:
            self.region_stack.append(self.brace_depth)
            self.function_stack.append(self.pending_function_name)
            self.pending_consteval = False
        if is_block_open and self.suppress_next_block_trap:
            self.suppress_next_block_trap = False
            self.last_token = "{"
            return "{"
        if self.in_consteval_region() and is_block_open:
            self._record_probe(line_number, line)
            # ";" so that a `return` following on the same line still counts
            # as starting a statement.
            self.last_token = ";"
            return "{ " + TRAP_CALL
        self.last_token = "{"
        return "{"

    def _on_close_brace(self) -> None:
        if self.region_stack and self.brace_depth == self.region_stack[-1]:
            self.region_stack.pop()
            self.function_stack.pop()
        if (
            self.runtime_lambda_stack
            and self.brace_depth == self.runtime_lambda_stack[-1]
        ):
            self.runtime_lambda_stack.pop()
        self.brace_depth -= 1


def find_googletest_include_directories() -> list[str]:
    """
    Locate googletest headers in the checkout CMake used.

    The sandbox image points FETCHCONTENT_SOURCE_DIR_GOOGLETEST at a baked-in
    checkout; elsewhere FetchContent clones under the build directory.
    """
    pattern = os.path.join(SOURCE_ROOT, "build", "*", "_deps", "googletest-src")
    candidates = [os.environ.get("FETCHCONTENT_SOURCE_DIR_GOOGLETEST", "")]
    candidates += sorted(glob.glob(pattern))
    for googletest_source in filter(None, candidates):
        include_directories = [
            os.path.join(googletest_source, "googletest", "include"),
            os.path.join(googletest_source, "googlemock", "include"),
        ]
        if all(os.path.isdir(directory) for directory in include_directories):
            return include_directories
    sys.exit(
        "googletest headers not found under build/*/_deps; run "
        "./scripts/cmake.sh build first"
    )


@dataclasses.dataclass
class ProbeConfiguration:
    """Everything needed to compile one probe."""

    compiler: str
    work_dir: str
    translation_units: list[str]
    include_directories: list[str]


def compile_command(
    configuration: ProbeConfiguration, translation_unit: str, armed_line: int
) -> list[str]:
    """Build the compiler command for one probe compile."""
    command = [
        configuration.compiler,
        "-std=c++26",
        "-freflection",
        "-fsyntax-only",
        "-w",
        "-include",
        os.path.join(configuration.work_dir, TRAP_HEADER),
        f"-DXYZ_CONSTEVAL_COVERAGE_ARMED_LINE={armed_line}",
        "-I",
        SOURCE_ROOT,
    ]
    for directory in configuration.include_directories:
        command.extend(["-I", directory])
    command.append(os.path.join(configuration.work_dir, translation_unit))
    return command


def run_probe(configuration: ProbeConfiguration, probe_point: ProbePoint) -> bool:
    """Return whether arming `probe_point` makes any translation unit fail."""
    for translation_unit in configuration.translation_units:
        completed = subprocess.run(
            compile_command(configuration, translation_unit, probe_point.line_number),
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            if TRAP_ERROR_MARKER not in completed.stderr:
                raise RuntimeError(
                    f"probe for {probe_point.header}:{probe_point.line_number} "
                    f"failed for a reason other than the armed trap:\n"
                    f"{completed.stderr}"
                )
            return True
    return False


def verify_unarmed_compile(configuration: ProbeConfiguration) -> None:
    """Check that the instrumented sources compile with no trap armed."""
    for translation_unit in configuration.translation_units:
        completed = subprocess.run(
            compile_command(configuration, translation_unit, armed_line=0),
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            sys.exit(
                f"instrumented {translation_unit} does not compile; the "
                f"instrumenter needs fixing:\n{completed.stderr}"
            )


def _is_covered(probe_point: ProbePoint, covered: set[tuple[str, int]]) -> bool:
    return (probe_point.header, probe_point.line_number) in covered


def write_lcov(
    path: str, probe_points: list[ProbePoint], covered: set[tuple[str, int]]
) -> None:
    """Write an LCOV trace with one SF/DA block per instrumented header."""
    by_header: dict[str, list[ProbePoint]] = {}
    for probe_point in probe_points:
        by_header.setdefault(probe_point.header, []).append(probe_point)

    records = ["TN:consteval"]
    for header in INSTRUMENTED_HEADERS:
        header_probes = by_header.get(header, [])
        if not header_probes:
            continue
        # Repository-relative SF path, matching how Codecov maps files.
        records.append(f"SF:{header}")
        header_hits = 0
        for probe_point in header_probes:
            hit = 1 if _is_covered(probe_point, covered) else 0
            header_hits += hit
            records.append(f"DA:{probe_point.line_number},{hit}")
        records.append(f"LH:{header_hits}")
        records.append(f"LF:{len(header_probes)}")
        records.append("end_of_record")
    with open(path, "w") as trace_file:
        trace_file.write("\n".join(records) + "\n")


def report(probe_points: list[ProbePoint], covered: set[tuple[str, int]]) -> None:
    """Print a per-function summary and the unevaluated probe points."""
    by_function: dict[tuple[str, str], list[ProbePoint]] = {}
    for probe_point in probe_points:
        key = (probe_point.header, probe_point.enclosing_function)
        by_function.setdefault(key, []).append(probe_point)

    print("\nconsteval coverage by header and function:")
    for (header, function_name), function_probes in by_function.items():
        hits = sum(1 for p in function_probes if _is_covered(p, covered))
        print(f"  {hits:3}/{len(function_probes):<3} {header}: {function_name}")

    uncovered = [p for p in probe_points if not _is_covered(p, covered)]
    if uncovered:
        print("\nprobe points never evaluated by the test suite:")
        for probe_point in uncovered:
            print(
                f"  {probe_point.header}:{probe_point.line_number:<4} "
                f"[{probe_point.enclosing_function}] {probe_point.source_text}"
            )

    total = len(probe_points)
    print(
        f"\nconsteval coverage: {len(covered)}/{total} probe points "
        f"evaluated ({100.0 * len(covered) / total:.1f}%)"
    )


def main() -> None:
    """Instrument each header in INSTRUMENTED_HEADERS and print a report."""
    parser = argparse.ArgumentParser(
        description="Measure consteval test coverage by compile-time trap probing."
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=os.cpu_count() or 1,
        help="Number of parallel probe compilations (default: CPU count)",
    )
    parser.add_argument(
        "--lcov-output",
        help="Also write the result as an LCOV trace file to this path",
    )
    parser.add_argument(
        "--work-dir",
        default=os.path.join(SOURCE_ROOT, "build", "consteval-coverage"),
        help="Directory for instrumented sources (default: build/consteval-coverage)",
    )
    parser.add_argument(
        "--translation-unit",
        action="append",
        help="Probe translation unit (repeatable; default: "
        + ", ".join(DEFAULT_TRANSLATION_UNITS)
        + ")",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List the probe points without compiling anything",
    )
    parser.add_argument(
        "--shard-count",
        type=int,
        default=1,
        help="Split probe points across this many shards (default: 1)",
    )
    parser.add_argument(
        "--shard-index",
        type=int,
        default=0,
        help="Which shard to probe, 0-based (default: 0)",
    )
    arguments = parser.parse_args()
    if not 0 <= arguments.shard_index < arguments.shard_count:
        sys.exit("--shard-index must be in [0, --shard-count)")

    all_probe_points: list[ProbePoint] = []
    source_by_header: dict[str, list[str]] = {}
    instrumented_by_header: dict[str, list[str]] = {}
    for header in INSTRUMENTED_HEADERS:
        with open(os.path.join(SOURCE_ROOT, header)) as header_file:
            source_by_header[header] = header_file.read().splitlines()
        instrumenter = Instrumenter(header)
        instrumented_by_header[header] = instrumenter.instrument(
            source_by_header[header]
        )
        all_probe_points.extend(instrumenter.probe_points)
    if not all_probe_points:
        sys.exit(f"no consteval probe points found in {INSTRUMENTED_HEADERS}")

    # Probe points are round-robined across shards rather than whole headers
    # being assigned to shards, because probe counts per header are far from
    # even (name_mangling.h alone accounts for roughly two fifths of them).
    probe_points = [
        probe_point
        for index, probe_point in enumerate(all_probe_points)
        if index % arguments.shard_count == arguments.shard_index
    ]
    if not probe_points:
        sys.exit(f"shard {arguments.shard_index} has no probe points to run")
    shard_headers = sorted(
        {probe_point.header for probe_point in probe_points},
        key=INSTRUMENTED_HEADERS.index,
    )

    if arguments.list:
        for probe_point in probe_points:
            print(
                f"{probe_point.header}:{probe_point.line_number:<4} "
                f"[{probe_point.enclosing_function}] {probe_point.source_text}"
            )
        return

    _, compiler = find_reflection_compilers(dict(os.environ))
    if compiler is None:
        sys.exit(
            "no reflection-capable compiler found (see scripts/compiler_discovery.py)"
        )

    translation_units = arguments.translation_unit or DEFAULT_TRANSLATION_UNITS
    include_directories = find_googletest_include_directories()

    # Each header is probed in its own work-dir subdirectory with only that
    # header instrumented, so a bare line number identifies a unique probe.
    # Every instrumented header is also written there in its plain,
    # uninstrumented form: quote-include resolution is relative to the
    # including file's own directory, so an instrumented header reached only
    # transitively (e.g. name_mangling.h via protocol.hh) would otherwise
    # resolve back to SOURCE_ROOT before reaching the target header's
    # directory. Headers outside INSTRUMENTED_HEADERS still fall through to
    # -I SOURCE_ROOT.
    probe_jobs: list[tuple[ProbeConfiguration, ProbePoint]] = []
    for header in shard_headers:
        header_work_dir = os.path.join(arguments.work_dir, header)
        os.makedirs(header_work_dir, exist_ok=True)
        for other_header in INSTRUMENTED_HEADERS:
            lines = (
                instrumented_by_header[other_header]
                if other_header == header
                else source_by_header[other_header]
            )
            with open(os.path.join(header_work_dir, other_header), "w") as out:
                out.write("\n".join(lines) + "\n")
        with open(os.path.join(header_work_dir, TRAP_HEADER), "w") as out:
            out.write(TRAP_HEADER_CONTENT)
        for translation_unit in translation_units:
            shutil.copy(
                os.path.join(SOURCE_ROOT, translation_unit),
                os.path.join(header_work_dir, translation_unit),
            )
        configuration = ProbeConfiguration(
            compiler=compiler,
            work_dir=header_work_dir,
            translation_units=translation_units,
            include_directories=include_directories,
        )
        verify_unarmed_compile(configuration)
        probe_jobs.extend(
            (configuration, probe_point)
            for probe_point in probe_points
            if probe_point.header == header
        )

    print(
        f"probing {len(probe_points)} consteval probe points across "
        f"{len(shard_headers)} headers against {len(translation_units)} "
        f"translation units with {arguments.jobs} jobs"
    )
    covered: set[tuple[str, int]] = set()
    with concurrent.futures.ThreadPoolExecutor(max_workers=arguments.jobs) as pool:
        futures = {
            pool.submit(run_probe, configuration, probe_point): probe_point
            for configuration, probe_point in probe_jobs
        }
        for future in concurrent.futures.as_completed(futures):
            if future.result():
                probe_point = futures[future]
                covered.add((probe_point.header, probe_point.line_number))

    report(probe_points, covered)
    if arguments.lcov_output:
        write_lcov(arguments.lcov_output, probe_points, covered)
        print(f"LCOV trace written to {arguments.lcov_output}")


if __name__ == "__main__":
    main()
