#!/usr/bin/env python3
"""
Measure which consteval code in protocol.hh the test suite evaluates.

`consteval` code executes inside the compiler's constant evaluator, never at
runtime, so runtime coverage tools cannot see it: GCC's `--coverage`
instrumentation marks every line of a consteval function as non-executable,
and a consteval function no test evaluates is indistinguishable from one that
is thoroughly tested. The community workaround for `constexpr` code - run
every test at both compile time and runtime so runtime instrumentation
observes it - is unavailable here: immediate functions cannot execute at
runtime, and calling a P2996 metafunction makes the caller immediate too.

This tool measures consteval coverage by compile-time trap probing. A
constant evaluation is isolated - no side effect escapes it - but it can
abort compilation, and that one bit per compile is enough:

1. Instrument a copy of protocol.hh, inserting a call to a `trap` function at
   the start of every block and before every `return` and `throw` statement
   inside consteval code. Insertions stay on the original line, so line
   numbers are unchanged. A trap is a no-op unless its line number is in the
   current round's armed set, in which case it throws during constant
   evaluation, failing the build with a recognisable, line-tagged error.
2. Compile the probe translation units with `-fsyntax-only` (constant
   evaluation happens during semantic analysis), arming every
   not-yet-resolved line at once. GCC does not stop at the first error: each
   independent top-level constant evaluation (roughly, each place the test
   suite forces protocol.hh's consteval machinery to run) throws at most
   once, reporting whichever armed line it reaches first along its own
   execution path, and every one of those independent failures is reported
   in the same compile.
3. A line armed alongside another that always executes first on every path
   that reaches it is masked: its own trap never runs because the earlier
   one already aborted that evaluation. Disarming every line the round just
   found and recompiling un-masks the next layer, so the process repeats
   until a round finds nothing new. The number of rounds is bounded by the
   deepest chain of always-together trap points in one execution path, not
   by the number of probe points.
4. Report evaluated and unevaluated probe points, optionally as an LCOV
   trace file that merges cleanly with runtime gcov data (the two are
   disjoint: gcov reports nothing for consteval lines).

Limitations: probe points sit at block and return/throw granularity, not on
every line; a branch of `if constexpr` that no instantiation includes is
reported unevaluated (correctly so); and a `catch (...)` that swallowed the
trap exception without rethrowing would mask probes beneath it (protocol.hh
has none).

Requires a reflection-capable GCC (found via compiler_discovery) and a prior
`./scripts/cmake.sh build` to provide the googletest headers.
"""

import argparse
import concurrent.futures
import dataclasses
import glob
import os
import re
import shutil
import subprocess
import sys

from compiler_discovery import find_reflection_compilers

SOURCE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Independent of the primary quote-style fix (trap_hit is now named by a
# template argument, not a runtime value): forcing the C locale keeps the
# rest of the compiler's output in plain ASCII too, regardless of the
# environment this script happens to run in.
COMPILER_ENVIRONMENT = dict(os.environ, LC_ALL="C")

INSTRUMENTED_HEADER = "protocol.hh"

TRAP_HEADER = "consteval_coverage_probe.h"

TRAP_CALL = "::xyz::consteval_coverage_probe::trap<__LINE__>();"

# The hit line is a template argument, not a runtime value inside `{}`: GCC
# renders it as plain digits inside `<>` in the uncaught-exception diagnostic
# regardless of locale (which affects whether surrounding quotes are ASCII or
# Unicode) or output format, so this match doesn't depend on the wording or
# punctuation of the diagnostic around it.
TRAP_ERROR_PATTERN = re.compile(r"xyz::consteval_coverage_probe::trap_hit<(\d+)>")

# Translation units that instantiate protocols and so drive the consteval
# machinery in protocol.hh.
DEFAULT_TRANSLATION_UNITS = [
    "protocol_test.cc",
    "forwarding_test.cc",
    "allocator_tests.cc",
]


def trap_header_content(armed_lines: frozenset[int]) -> str:
    """
    Regenerate the whole trap header for one round, baking in the armed set.

    Regenerated (not incrementally patched) because it is a handful of
    lines regardless of how many probe points exist; the cost that scales
    with probe count lives in the armed-set lookup, not in this file.
    """
    sorted_lines = ", ".join(str(line) for line in sorted(armed_lines))
    return f"""\
// Generated by scripts/consteval_coverage.py; force-included into the
// instrumented translation units via -include.

namespace xyz::consteval_coverage_probe {{

// Deliberately not derived from std::exception, so that no typed catch in
// the library or its tests can swallow it. Parameterised on Line, rather
// than carrying it as a runtime field, so the compiler's uncaught-exception
// diagnostic renders the hit line as plain digits in the type's name; a
// runtime field only shows up inside the diagnostic's braced-init rendering
// of the value, whose surrounding punctuation is locale-dependent.
template <long Line>
struct trap_hit {{}};

constexpr bool is_armed(long line) {{
  constexpr long armed_lines[] = {{{sorted_lines}}};
  for (long armed : armed_lines) {{
    if (armed == line) return true;
  }}
  return false;
}}

template <long Line>
constexpr void trap() {{
  if consteval {{
    if (is_armed(Line)) throw trap_hit<Line>{{}};
  }}
}}

}}  // namespace xyz::consteval_coverage_probe
"""

# Tokens whose presence directly before `{` marks it as opening a compound
# statement rather than a braced initialiser. `)` covers control clauses,
# function signatures and lambdas; `consteval` covers consteval blocks.
BLOCK_OPEN_TOKENS = {")", "else", "try", "do", "consteval"}

# Tokens after which a `return` or `throw` token starts a statement.
STATEMENT_START_TOKENS = {";", "{", "}", ")", ":", "else", "do"}


@dataclasses.dataclass
class ProbePoint:
    """One instrumented location in the original source."""

    line_number: int
    enclosing_function: str
    source_text: str


class Instrumenter:
    """
    Insert coverage traps into the consteval regions of a C++ header.

    A hand-rolled scanner rather than a real C++ parser: it tracks strings,
    comments, brace depth and consteval regions, which the clang-formatted
    source keeps tractable. It only ever inserts text within a line, so the
    instrumented file has the same line numbers as the original.
    Unrecognised constructs are left uninstrumented (under-measurement,
    never miscompilation), and the prober verifies that the instrumented
    file still compiles before probing.
    """

    def __init__(self) -> None:
        """Initialise scanner state."""
        self.brace_depth = 0
        self.paren_depth = 0
        # Brace depths at which enclosing consteval regions opened, and the
        # name of the consteval function each region belongs to.
        self.region_stack: list[int] = []
        self.function_stack: list[str] = []
        # A `consteval` token was seen; the next block-opening `{` starts a
        # region named `pending_function_name` (the identifier before the
        # first `(` of the pending declaration, if any).
        self.pending_consteval = False
        self.pending_function_name = ""
        self.pending_name_frozen = False
        self.in_block_comment = False
        # Set when a `switch` header is seen; its block gets no entry trap
        # because a statement before the first case label is unreachable.
        self.suppress_next_block_trap = False
        self.last_token = ""
        # While wrapping `return expr;` as `{ trap; return expr; }`: the
        # parenthesis/bracket nesting until the terminating `;`.
        self.wrap_nesting: int | None = None
        # `+[` introduces a captureless lambda converted to a function
        # pointer: a runtime thunk stored in a vtable. Its body executes at
        # runtime (gcov's domain, not the constant evaluator's), so probes
        # inside it are suppressed. The stack holds the brace depth of each
        # such lambda body.
        self.pending_runtime_lambda = False
        self.runtime_lambda_stack: list[int] = []
        self.probe_points: list[ProbePoint] = []

    def in_consteval_region(self) -> bool:
        """Return whether the scanner is inside compile-time-evaluated code."""
        return bool(self.region_stack) and not self.runtime_lambda_stack

    def instrument(self, source_lines: list[str]) -> list[str]:
        """Return instrumented copies of `source_lines` (without newlines)."""
        return [
            self._instrument_line(line, line_number)
            for line_number, line in enumerate(source_lines, start=1)
        ]

    def _record_probe(self, line_number: int, original_line: str) -> None:
        enclosing = self.function_stack[-1] if self.function_stack else "<none>"
        if self.pending_consteval:
            enclosing = self.pending_function_name
        if not self.probe_points or self.probe_points[-1].line_number != line_number:
            self.probe_points.append(
                ProbePoint(line_number, enclosing, original_line.strip())
            )

    def _instrument_line(self, line: str, line_number: int) -> str:
        if not self.in_block_comment and line.lstrip().startswith("#"):
            return line
        output: list[str] = []
        index = 0
        while index < len(line):
            if self.in_block_comment:
                end = line.find("*/", index)
                if end == -1:
                    output.append(line[index:])
                    break
                output.append(line[index : end + 2])
                index = end + 2
                self.in_block_comment = False
                continue
            character = line[index]
            if character.isalpha() or character == "_":
                end = index + 1
                while end < len(line) and (line[end].isalnum() or line[end] == "_"):
                    end += 1
                token = line[index:end]
                output.append(self._on_token(token, line, line_number))
                index = end
                continue
            if line.startswith("//", index):
                output.append(line[index:])
                break
            if line.startswith("/*", index):
                output.append("/*")
                index += 2
                self.in_block_comment = True
                continue
            if character == '"' or (
                character == "'"
                and not (
                    index > 0 and (line[index - 1].isalnum() or line[index - 1] == "_")
                )
            ):
                end = self._literal_end(line, index, character)
                output.append(line[index:end])
                index = end
                continue
            output.append(self._on_punctuation(character, line, line_number))
            index += 1
        return "".join(output)

    def _literal_end(self, line: str, start: int, quote: str) -> int:
        index = start + 1
        while index < len(line):
            if line[index] == "\\":
                index += 2
                continue
            if line[index] == quote:
                return index + 1
            index += 1
        return index

    def _on_token(self, token: str, line: str, line_number: int) -> str:
        prefix = ""
        if token == "consteval" and self.wrap_nesting is None:
            self.pending_consteval = True
            self.pending_name_frozen = False
            self.pending_function_name = f"<consteval block at line {line_number}>"
        elif token == "switch":
            self.suppress_next_block_trap = True
        elif (
            token in ("return", "throw")
            and self.in_consteval_region()
            and self.wrap_nesting is None
            and self.last_token in STATEMENT_START_TOKENS
        ):
            self._record_probe(line_number, line)
            prefix = "{ " + TRAP_CALL + " "
            self.wrap_nesting = 0
        elif (
            self.pending_consteval
            and not self.pending_name_frozen
            and token not in ("consteval", "static")
        ):
            self.pending_function_name = token
        self.last_token = token
        return prefix + token

    def _on_punctuation(self, character: str, line: str, line_number: int) -> str:
        if character == "{":
            return self._on_open_brace(line, line_number)
        if character == "}":
            self._on_close_brace()
            self.last_token = "}"
            return "}"
        if character in "([":
            if character == "(" and self.pending_consteval:
                self.pending_name_frozen = True
            if character == "[" and self.last_token == "+":
                self.pending_runtime_lambda = True
            self.paren_depth += 1
            if self.wrap_nesting is not None:
                self.wrap_nesting += 1
        elif character in ")]":
            self.paren_depth -= 1
            if self.wrap_nesting is not None:
                self.wrap_nesting -= 1
        elif character == ";":
            if self.wrap_nesting == 0:
                self.wrap_nesting = None
                self.last_token = ";"
                return "; }"
            if self.paren_depth == 0 and self.brace_depth == 0:
                # A declaration (e.g. a forward declaration) ended before any
                # body opened; it cannot start a consteval region.
                self.pending_consteval = False
        if not character.isspace():
            self.last_token = character
        return character

    def _on_open_brace(self, line: str, line_number: int) -> str:
        self.brace_depth += 1
        if self.pending_runtime_lambda:
            # The first `{` after `+[` is the lambda body: a captureless
            # lambda's capture list and parameter list cannot contain braces.
            self.runtime_lambda_stack.append(self.brace_depth)
            self.pending_runtime_lambda = False
            self.last_token = "{"
            return "{"
        is_block_open = self.last_token in BLOCK_OPEN_TOKENS
        if self.pending_consteval and is_block_open:
            self.region_stack.append(self.brace_depth)
            self.function_stack.append(self.pending_function_name)
            self.pending_consteval = False
        if is_block_open and self.suppress_next_block_trap:
            self.suppress_next_block_trap = False
            self.last_token = "{"
            return "{"
        if self.in_consteval_region() and is_block_open:
            self._record_probe(line_number, line)
            # ";" so that a `return` following on the same line still counts
            # as starting a statement.
            self.last_token = ";"
            return "{ " + TRAP_CALL
        self.last_token = "{"
        return "{"

    def _on_close_brace(self) -> None:
        if self.region_stack and self.brace_depth == self.region_stack[-1]:
            self.region_stack.pop()
            self.function_stack.pop()
        if (
            self.runtime_lambda_stack
            and self.brace_depth == self.runtime_lambda_stack[-1]
        ):
            self.runtime_lambda_stack.pop()
        self.brace_depth -= 1


def find_googletest_include_directories() -> list[str]:
    """Locate googletest headers under an existing CMake build directory."""
    pattern = os.path.join(SOURCE_ROOT, "build", "*", "_deps", "googletest-src")
    for googletest_source in sorted(glob.glob(pattern)):
        include_directories = [
            os.path.join(googletest_source, "googletest", "include"),
            os.path.join(googletest_source, "googlemock", "include"),
        ]
        if all(os.path.isdir(directory) for directory in include_directories):
            return include_directories
    sys.exit(
        "googletest headers not found under build/*/_deps; run "
        "./scripts/cmake.sh build first"
    )


@dataclasses.dataclass
class ProbeConfiguration:
    """Everything needed to compile one probe."""

    compiler: str
    work_dir: str
    translation_units: list[str]
    include_directories: list[str]


def compile_command(
    configuration: ProbeConfiguration, translation_unit: str, trap_header_path: str
) -> list[str]:
    """Build the compiler command for compiling one translation unit."""
    command = [
        configuration.compiler,
        "-std=c++26",
        "-freflection",
        "-fsyntax-only",
        "-w",
        "-include",
        trap_header_path,
        "-I",
        SOURCE_ROOT,
    ]
    for directory in configuration.include_directories:
        command.extend(["-I", directory])
    command.append(os.path.join(configuration.work_dir, translation_unit))
    return command


def compile_batch(
    configuration: ProbeConfiguration,
    translation_unit: str,
    batch_id: int,
    armed_lines: frozenset[int],
) -> set[int]:
    """
    Compile one translation unit with one batch of the round's armed set.

    Every independent top-level constant evaluation that reaches an armed
    line throws at most once, so a single compile can report many distinct
    hits (one per evaluation), not just one. Each batch gets its own trap
    header file so batches of the same translation unit can compile in
    parallel without clobbering each other's -include target.
    """
    trap_header_path = os.path.join(
        configuration.work_dir, f"{translation_unit}.batch{batch_id}.{TRAP_HEADER}"
    )
    with open(trap_header_path, "w") as out:
        out.write(trap_header_content(armed_lines))
    completed = subprocess.run(
        compile_command(configuration, translation_unit, trap_header_path),
        capture_output=True,
        text=True,
        env=COMPILER_ENVIRONMENT,
    )
    hits = {int(line) for line in TRAP_ERROR_PATTERN.findall(completed.stderr)}
    if completed.returncode != 0 and not hits:
        raise RuntimeError(
            f"compiling {translation_unit} failed for a reason other than "
            f"an armed trap:\n{completed.stderr}"
        )
    return hits


def batches(armed_lines: set[int], batch_count: int) -> list[frozenset[int]]:
    """Split armed_lines into batch_count roughly-equal chunks."""
    batch_count = max(1, min(batch_count, len(armed_lines)))
    batch_size = -(-len(armed_lines) // batch_count)  # ceiling division
    sorted_lines = sorted(armed_lines)
    return [
        frozenset(sorted_lines[start : start + batch_size])
        for start in range(0, len(sorted_lines), batch_size)
    ]


def probe_all_lines(
    configuration: ProbeConfiguration,
    probe_points: list[ProbePoint],
    jobs: int,
) -> set[int]:
    """
    Find every probe line the test suite evaluates, in as few compiles as
    possible.

    Each round arms every line not yet known to be covered, splits it into
    enough batches per translation unit that the total number of compiles
    this round is about `jobs` (so every worker has one to run without
    splitting more finely than that), and compiles every translation unit
    against every batch. A line masked behind an earlier trap on the same
    execution path surfaces once that earlier trap is disarmed in a later
    round. Rounds stop once one of them finds nothing new, which bounds the
    round count by the deepest chain of always-together trap points on a
    single execution path, not by the number of probe points.
    """
    all_lines = {probe_point.line_number for probe_point in probe_points}
    covered_lines: set[int] = set()
    batches_per_translation_unit = -(-jobs // len(configuration.translation_units))
    round_number = 0
    while True:
        round_number += 1
        armed_lines = all_lines - covered_lines
        if not armed_lines:
            break
        line_batches = batches(armed_lines, batches_per_translation_unit)

        new_hits: set[int] = set()
        with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as pool:
            futures = [
                pool.submit(compile_batch, configuration, translation_unit, batch_id, batch)
                for translation_unit in configuration.translation_units
                for batch_id, batch in enumerate(line_batches)
            ]
            for future in concurrent.futures.as_completed(futures):
                new_hits |= future.result()
        new_hits &= armed_lines  # ignore stray matches from stale/other output

        print(
            f"round {round_number}: {len(armed_lines)} lines armed, "
            f"{len(new_hits)} newly covered"
        )
        if not new_hits:
            break
        covered_lines |= new_hits
    return covered_lines


def write_lcov(
    path: str, probe_points: list[ProbePoint], covered_lines: set[int]
) -> None:
    """Write an LCOV trace with one DA record per probe point."""
    # Repository-relative SF path, matching how Codecov maps files.
    records = ["TN:consteval", f"SF:{INSTRUMENTED_HEADER}"]
    for probe_point in probe_points:
        hit = 1 if probe_point.line_number in covered_lines else 0
        records.append(f"DA:{probe_point.line_number},{hit}")
    records.append(f"LH:{len(covered_lines)}")
    records.append(f"LF:{len(probe_points)}")
    records.append("end_of_record")
    with open(path, "w") as trace_file:
        trace_file.write("\n".join(records) + "\n")


def report(probe_points: list[ProbePoint], covered_lines: set[int]) -> None:
    """Print a per-function summary and the unevaluated probe points."""
    by_function: dict[str, list[ProbePoint]] = {}
    for probe_point in probe_points:
        by_function.setdefault(probe_point.enclosing_function, []).append(probe_point)

    print(f"\nconsteval coverage of {INSTRUMENTED_HEADER}, by function:")
    for function_name, function_probes in by_function.items():
        hits = sum(1 for p in function_probes if p.line_number in covered_lines)
        print(f"  {hits:3}/{len(function_probes):<3} {function_name}")

    uncovered = [p for p in probe_points if p.line_number not in covered_lines]
    if uncovered:
        print("\nprobe points never evaluated by the test suite:")
        for probe_point in uncovered:
            print(
                f"  {INSTRUMENTED_HEADER}:{probe_point.line_number:<4} "
                f"[{probe_point.enclosing_function}] {probe_point.source_text}"
            )

    total = len(probe_points)
    print(
        f"\nconsteval coverage: {len(covered_lines)}/{total} probe points "
        f"evaluated ({100.0 * len(covered_lines) / total:.1f}%)"
    )


def main() -> None:
    """Instrument protocol.hh, probe every trap line and print a report."""
    parser = argparse.ArgumentParser(
        description="Measure consteval test coverage by compile-time trap probing."
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=os.cpu_count() or 1,
        help="Number of parallel probe compilations (default: CPU count)",
    )
    parser.add_argument(
        "--lcov-output",
        help="Also write the result as an LCOV trace file to this path",
    )
    parser.add_argument(
        "--work-dir",
        default=os.path.join(SOURCE_ROOT, "build", "consteval-coverage"),
        help="Directory for instrumented sources (default: build/consteval-coverage)",
    )
    parser.add_argument(
        "--translation-unit",
        action="append",
        help="Probe translation unit (repeatable; default: "
        + ", ".join(DEFAULT_TRANSLATION_UNITS)
        + ")",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List the probe points without compiling anything",
    )
    arguments = parser.parse_args()

    with open(os.path.join(SOURCE_ROOT, INSTRUMENTED_HEADER)) as header_file:
        source_lines = header_file.read().splitlines()
    instrumenter = Instrumenter()
    instrumented_lines = instrumenter.instrument(source_lines)
    probe_points = instrumenter.probe_points
    if not probe_points:
        sys.exit(f"no consteval probe points found in {INSTRUMENTED_HEADER}")

    if arguments.list:
        for probe_point in probe_points:
            print(
                f"{INSTRUMENTED_HEADER}:{probe_point.line_number:<4} "
                f"[{probe_point.enclosing_function}] {probe_point.source_text}"
            )
        return

    _, compiler = find_reflection_compilers(dict(os.environ))
    if compiler is None:
        sys.exit(
            "no reflection-capable compiler found (see scripts/compiler_discovery.py)"
        )

    translation_units = arguments.translation_unit or DEFAULT_TRANSLATION_UNITS
    os.makedirs(arguments.work_dir, exist_ok=True)
    with open(os.path.join(arguments.work_dir, INSTRUMENTED_HEADER), "w") as out:
        out.write("\n".join(instrumented_lines) + "\n")
    # The translation units are copied next to the instrumented header so
    # that their `#include "protocol.hh"` finds the instrumented copy first;
    # every other quote-include falls through to -I SOURCE_ROOT.
    for translation_unit in translation_units:
        shutil.copy(
            os.path.join(SOURCE_ROOT, translation_unit),
            os.path.join(arguments.work_dir, translation_unit),
        )

    configuration = ProbeConfiguration(
        compiler=compiler,
        work_dir=arguments.work_dir,
        translation_units=translation_units,
        include_directories=find_googletest_include_directories(),
    )

    print(
        f"probing {len(probe_points)} consteval probe points against "
        f"{len(translation_units)} translation units with {arguments.jobs} jobs"
    )
    covered_lines = probe_all_lines(configuration, probe_points, arguments.jobs)

    report(probe_points, covered_lines)
    if arguments.lcov_output:
        write_lcov(arguments.lcov_output, probe_points, covered_lines)
        print(f"LCOV trace written to {arguments.lcov_output}")


if __name__ == "__main__":
    main()
