#!/usr/bin/env python3
"""
Generates protocol_reflection_detail/operator_forwarders.h.

An interface operator's forwarder must declare a real `operator<symbol>`
member, and the operator symbol has to appear as a literal token in that
declaration: there is currently no way to reflect a std::meta::operators
enumerator into the declarator-id of a new operator overload (the same
limitation https://github.com/RyanJK5/rjk-duck works around with its own
generate_operators.py, generating do_unary_op.hpp/do_binary_op.hpp/
operator_friends.inl). This script performs the equivalent one-time,
offline generation for xyz::protocol's operator_forwarder/operator_join
specializations, instead of a C-preprocessor macro expanded on every build.

Run with `uv run python3 scripts/generate_operator_forwarders.py` after
changing the OPERATORS table below, then let pre-commit's clang-format hook
reformat the output.
"""

import os
import subprocess

# (operator symbol, std::meta::operators enumerator, is_nullary). Nullary
# operators (-> ~ !) are declared with no parameter list at all; declaring
# them with an (always-empty) parameter pack is rejected.
OPERATORS = [
    ("=", "op_equals", False),
    ("()", "op_parentheses", False),
    ("[]", "op_square_brackets", False),
    ("->", "op_arrow", True),
    ("->*", "op_arrow_star", False),
    ("~", "op_tilde", True),
    ("!", "op_exclamation", True),
    ("+", "op_plus", False),
    ("-", "op_minus", False),
    ("*", "op_star", False),
    ("/", "op_slash", False),
    ("%", "op_percent", False),
    ("^", "op_caret", False),
    ("&", "op_ampersand", False),
    ("|", "op_pipe", False),
    ("+=", "op_plus_equals", False),
    ("-=", "op_minus_equals", False),
    ("*=", "op_star_equals", False),
    ("/=", "op_slash_equals", False),
    ("%=", "op_percent_equals", False),
    ("^=", "op_caret_equals", False),
    ("&=", "op_ampersand_equals", False),
    ("|=", "op_pipe_equals", False),
    ("==", "op_equals_equals", False),
    ("!=", "op_exclamation_equals", False),
    ("<", "op_less", False),
    (">", "op_greater", False),
    ("<=", "op_less_equals", False),
    (">=", "op_greater_equals", False),
    ("<=>", "op_spaceship", False),
    ("&&", "op_ampersand_ampersand", False),
    ("||", "op_pipe_pipe", False),
    ("<<", "op_less_less", False),
    (">>", "op_greater_greater", False),
    ("<<=", "op_less_less_equals", False),
    (">>=", "op_greater_greater_equals", False),
    ("++", "op_plus_plus", False),
    ("--", "op_minus_minus", False),
    (",", "op_comma", False),
]

OUTPUT_PATH = "protocol_reflection_detail/operator_forwarders.h"

HEADER = """/* Copyright (c) 2026 The XYZ Protocol Authors. All Rights Reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
==============================================================================*/
// ============================================================================
// AUTOMATICALLY GENERATED FILE - DO NOT MODIFY
// ============================================================================
// This file was generated by scripts/generate_operator_forwarders.py.
//
// One operator_forwarder specialization pair (non-const, const) plus one
// operator_join specialization per operator kind, for the C++26 reflection
// backend: forwarding an interface operator requires a real `operator<symbol>`
// declaration, and the symbol must appear as a literal token in source, so
// each kind is generated once here rather than reimplemented by hand.
//
// Any manual changes made to this file will be overwritten during the next
// generation run.
// ============================================================================
#ifndef XYZ_PROTOCOL_REFLECTION_DETAIL_OPERATOR_FORWARDERS_H_
#define XYZ_PROTOCOL_REFLECTION_DETAIL_OPERATOR_FORWARDERS_H_

#ifndef __cpp_impl_reflection
#error \\
    "This header requires a compiler with C++26 reflection support (GCC 16+, \
-std=c++26 -freflection)."
#endif

#include <meta>
#include <utility>

namespace xyz {
namespace reflection_detail {

using std::meta::info;

template <typename Owner, info Member, typename Signature,
          std::meta::operators Kind, bool ConstCall, bool IsNoexcept>
struct operator_forwarder;

// One join per operator kind gathers every overload of that kind into a
// single class: name lookup for e.g. `operator+` across multiple distinct
// bases would be ambiguous, so the overloads must be merged with
// using-declarations, which also require the operator symbol literally.
template <std::meta::operators Kind, typename... Forwarders>
struct operator_join;

"""

FOOTER = """
}  // namespace reflection_detail
}  // namespace xyz

#endif  // XYZ_PROTOCOL_REFLECTION_DETAIL_OPERATOR_FORWARDERS_H_
"""

NARY_TEMPLATE = """\
template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::{kind}, false, IsNoexcept> {{
  ReturnType operator{symbol}(ParameterTypes... parameters) noexcept(
      IsNoexcept) {{
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }}
}};

template <typename Owner, info Member, typename ReturnType,
          typename... ParameterTypes, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(ParameterTypes...),
                          std::meta::operators::{kind}, true, IsNoexcept> {{
  ReturnType operator{symbol}(ParameterTypes... parameters) const
      noexcept(IsNoexcept) {{
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>(
        std::forward<ParameterTypes>(parameters)...);
  }}
}};

template <typename... Forwarders>
struct operator_join<std::meta::operators::{kind}, Forwarders...>
    : Forwarders... {{
  using Forwarders::operator{symbol}...;
}};
"""

NULLARY_TEMPLATE = """\
template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::{kind}, false, IsNoexcept> {{
  ReturnType operator{symbol}() noexcept(IsNoexcept) {{
    auto* owner = static_cast<Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }}
}};

template <typename Owner, info Member, typename ReturnType, bool IsNoexcept>
struct operator_forwarder<Owner, Member, ReturnType(),
                          std::meta::operators::{kind}, true, IsNoexcept> {{
  ReturnType operator{symbol}() const noexcept(IsNoexcept) {{
    const auto* owner = static_cast<const Owner*>(this);
    return owner->template dispatch_reflected_member<Member>();
  }}
}};

template <typename... Forwarders>
struct operator_join<std::meta::operators::{kind}, Forwarders...>
    : Forwarders... {{
  using Forwarders::operator{symbol}...;
}};
"""


def main() -> None:
    """Generate operator_forwarders.h from the OPERATORS table."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    workspace_root = os.path.dirname(script_dir)
    output_path = os.path.join(workspace_root, OUTPUT_PATH)

    blocks = []
    for symbol, kind, is_nullary in OPERATORS:
        template = NULLARY_TEMPLATE if is_nullary else NARY_TEMPLATE
        blocks.append(f"// {kind}\n" + template.format(symbol=symbol, kind=kind))

    with open(output_path, "w") as f:
        f.write(HEADER + "\n".join(blocks) + FOOTER)

    subprocess.run(["clang-format", "-i", output_path], check=True)
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
