name: Clang Tidy

on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  COMPILER_VERSION: 21

jobs:
  clang-tidy:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Clang
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ env.COMPILER_VERSION }} all

          # We need to update symlink otherwise we end up with miss matched clang/clang++ and clang-tidy versions.
          sudo rm /usr/bin/clang
          sudo rm /usr/bin/clang++
          sudo rm /usr/bin/clang-tidy

          sudo ln -s /usr/bin/clang-${{ env.COMPILER_VERSION }} /usr/bin/clang
          sudo ln -s /usr/bin/clang++-${{ env.COMPILER_VERSION }} /usr/bin/clang++
          sudo ln -s /usr/bin/clang-tidy-${{ env.COMPILER_VERSION }} /usr/bin/clang-tidy
      - name: Configure CMake
        run: cmake --preset ${{ matrix.configuration }} -DCLANG_TIDY_ENABLE=1
      - name: Build
        # Build your program with the given configuration
        run: cmake --build --preset ${{ matrix.configuration }}
